name: SkittleCities
version: '${version}'
main: twotoz.skittleCities.SkittleCities
api-version: '1.21'
author: TwoToz
description: Advanced claim and city management plugin

commands:
  ctool:
    description: Get the region selection tool
    usage: /ctool
    permission: skittlecities.admin
    
  cregioncreate:
    description: Create a new region from your selection
    usage: /cregioncreate
    permission: skittlecities.admin
    
  cflags:
    description: Manage flags for claims or the world
    usage: /cflags
    permission: skittlecities.admin
    
  ctrust:
    description: Trust a player in your claim (claim owners can use this, admins can use in any claim)
    usage: /ctrust <player>
    
  cuntrust:
    description: Untrust a player from your claim (claim owners can use this, admins can use in any claim)
    usage: /cuntrust <player>
    
  cbal:
    description: Check your balance
    usage: /cbal
    permission: skittlecities.player
    
  cbaltop:
    description: View the richest players (top 10 by default)
    usage: /cbaltop [limit]
    permission: skittlecities.player
    
  cdebugtool:
    description: Toggle claim visualization (admin only)
    usage: /cdebugtool
    permission: skittlecities.admin
    
  cignoreclaims:
    description: Toggle bypassing claim protections
    usage: /cignoreclaims
    permission: skittlecities.admin
    
  cautoextend:
    description: Toggle auto-extend for your leased claim
    usage: /cautoextend
    permission: skittlecities.player
    
  cclaims:
    description: View and manage all your claims
    usage: /cclaims
    permission: skittlecities.player
    
  city:
    description: Teleport to the city
    usage: /city
    permission: skittlecities.player
    aliases: [cspawn]
    
  leavecity:
    description: Leave the city and return to server spawn
    usage: /leavecity
    permission: skittlecities.player
    
  cmenu:
    description: Open the main menu
    usage: /cmenu
    permission: skittlecities.player
    aliases: [menu]
    
  setcityspawn:
    description: Set the city spawn location
    usage: /setcityspawn
    permission: skittlecities.admin
    
  setleavespawn:
    description: Set the spawn location for /leavecity command
    usage: /setleavespawn
    permission: skittlecities.admin
    
  ceconomy:
    description: Manage player economy
    usage: /ceconomy <give|take|set> <player> <amount>
    permission: skittlecities.admin
    
  cadmin:
    description: View and manage all claims
    usage: /cadmin
    permission: skittlecities.admin
    
  citycommandbypass:
    description: Toggle command restrictions in the city
    usage: /citycommandbypass
    permission: skittlecities.commandbypass
    aliases: [ccbypass]
    
  csellsign:
    description: Create a SELL sign where players can BUY items from the server (admin only)
    usage: /csellsign <material> <price>
    permission: skittlecities.admin
    
  cbuysign:
    description: Create a BUY sign where players can SELL items to the server (admin only)
    usage: /cbuysign <material> <price>
    permission: skittlecities.admin
    
  crename:
    description: Rename a claim (admin only)
    usage: /crename <name>
    permission: skittlecities.admin
    
  csubclaim:
    description: Create a subclaim within a claim (admin only)
    usage: /csubclaim <name>
    permission: skittlecities.admin
    
  csubclaims:
    description: List subclaims of a claim (admin only)
    usage: /csubclaims
    permission: skittlecities.admin
    
  creload:
    description: Reload the plugin configuration (admin only)
    usage: /creload
    permission: skittlecities.admin
    
  cgetmenuitem:
    description: Get the menu item (for testing)
    usage: /cgetmenuitem
    permission: skittlecities.player
    
  cmigrate:
    description: Migrate database - add missing flags to existing claims (admin only)
    usage: /cmigrate
    permission: skittlecities.admin

permissions:
  skittlecities.admin:
    description: Grants access to all admin commands
    default: op
    children:
      skittlecities.player: true
      skittlecities.admintrust: true
      skittlecities.debug: true
      skittlecities.commandbypass: true
      skittlecities.balance.others: true
      skittlecities.fly: true
      
  skittlecities.player:
    description: Basic player permissions
    default: true
    
  skittlecities.admintrust:
    description: Allows trusting/untrusting players in ANY claim (admin override - claim owners can always trust in their own claims)
    default: op
    
  skittlecities.balance.others:
    description: Allows viewing other players' balances
    default: op
    
  skittlecities.debug:
    description: Allows using debug visualization (admin only)
    default: op
    
  skittlecities.commandbypass:
    description: Allows bypassing city command restrictions
    default: op
    
  skittlecities.fly:
    description: Allows flying in the city world
    default: op
